.github/workflows/ci.yml
Makefile
env.sh
environment.yml
utils/quiet_cmd.sh

gh-actions: add license check

---

.github/kokoro/test.sh

kokoro: fix test script

---

.github/kokoro/continuous.cfg
.github/kokoro/presubmit.cfg

kokoro: fix artifacts regexp

---

tests/features/CMakeLists.txt
tests/features/pll/CMakeLists.txt
tests/features/pll/basys3.xdc
tests/features/pll/pll_tb.v
tests/features/pll/pll_top.v
tests/features/pll/plle2_test.v
tests/tests.cmake

Adds basic PLL test with the corresponding testbench.
This PR is based on https://github.com/SymbiFlow/fpga-interchange-tests/pull/21

Add pll test

---

CMakeLists.txt
README.md
tests/tests.cmake
utils/utils.cmake

cmake: enable overriding of tools binaries to ease developement

---

.gitmodules
Makefile
environment.yml

env: use prjoxide from conda

---

requirements.txt

requirements: use rapidyaml from PyPI

---

tests/features/serdes/serdes.v
tests/features/serdes/serdes_test.v

tests: serdes: fix initial assignments

---

.github/kokoro/steps/hostsetup.sh
.github/kokoro/steps/xilinx.sh
.github/kokoro/test.sh
CMakeLists.txt
tests/arch_tests.cmake
tests/features/serdes/serdes.v

kokoro: test vivado 2019.2

---

boards/CMakeLists.txt
boards/boards.cmake
devices/CMakeLists.txt
devices/chipdb_xilinx.cmake
devices/xczu7ev/CMakeLists.txt
tests/arch_tests.cmake
tests/common/dcp_vivado.tcl
tests/common/remap_xcup.v
tests/common/synth_xcup.tcl
tests/common/vivado.tcl
tests/features/wire/CMakeLists.txt
tests/features/wire/zcu104.xdc
tests/tests.cmake

This currently gets as far as generating a chipdb, with https://github.com/SymbiFlow/python-fpga-interchange/pull/105 and verification patched out of RapidWright due to https://github.com/Xilinx/RapidWright/issues/194.
I'm now working on getting the wire test to actually build.

UltraScale+ test with ZCU104

---

.github/workflows/ci.yml

Signed-off-by: Adam Olech <aolech@antmicro.com>

CI: use self-hosted runners

---

environment.yml

bump nextpnr-interchange and python-interchange

---

requirements.txt

requirements: add edit mode when installing third_party

---

.gitmodules
devices/chipdb_testarch.cmake

This PR also moves the submodules to point to the new chipsalliance upstream repository

testarch: remove LUT definitions patching step

---

devices/chipdb_testarch.cmake

Signed-off-by: Maciej Dudek <mdudek@antmicro.com>

Move lutDefinition into generation step

---

.github/workflows/ci.yml
boards/CMakeLists.txt
devices/CMakeLists.txt
devices/xc7k160t/CMakeLists.txt
devices/xc7k70t/CMakeLists.txt
tests/designs/counter/CMakeLists.txt
tests/designs/counter/xc7k160t_board.xdc
tests/designs/counter/xc7k70t_board.xdc
tests/designs/murax/CMakeLists.txt
tests/designs/murax/arty_s7_50.xdc
tests/designs/murax/xc7k70t_board.xdc
tests/designs/murax/xc7k70t_board_toplevel.v
tests/designs/picosoc/CMakeLists.txt
tests/designs/picosoc/xc7k70t_board.xdc
third_party/picosoc/xc7k70t_board.v

This adds tests for Kintex7 FPGAs (70t and 160t).

Add tests for Kintex-7

---

utils/aggregate_results.py

results: fix plot graph in web report

---

.github/workflows/ci.yml
Makefile
tests/designs/counter/CMakeLists.txt
tests/features/lut/CMakeLists.txt
tests/features/wire/CMakeLists.txt

This PR should fix https://github.com/chipsalliance/fpga-interchange-tests/issues/94 and apply the fixes from RW

Bump RapidWright

---

tests/features/pll/CMakeLists.txt
tests/features/pll/plle4_adv.v
tests/features/pll/util.v
tests/features/pll/zcu104.xdc

Part of #97. It should be working after merging https://github.com/chipsalliance/python-fpga-interchange/pull/148

PLLE4 test for ZCU104

---

.github/workflows/ci.yml
.github/workflows/update_conda_lock.yml
Makefile
README.md
conda_lock.yml
requirements.txt

This PR does the following:
- updates README
- fixes rapidyaml python requirements
- updates requirements to point to correct git repos
- adds a cron job to run every day
- adds workflow to upate the conda packages on a daily bases and open a PR with the updated packages

Run cron CI

---

.github/scripts/centos-setup.sh
.github/scripts/generate_job_matrix.py
.github/scripts/ubuntu-setup.sh
.github/workflows/ci.yml
tests/designs/litex_linux/CMakeLists.txt
tests/designs/litex_linux/arty.v
tests/tests.cmake
utils/aggregate_results.py
utils/report_targets.py

This PR refactors CI to include a job matrix generation, also adding a step to build everything using centOS 7 as a different OS.

Refactor CI to add centOS 7

---

.github/scripts/centos-setup.sh
.github/scripts/ubuntu-setup.sh

Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>

Add set -e to setup bash scripts
